name: Create Release and Build Android

on:
  push:
    branches:
      - main

jobs:
  create_release_and_build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
            git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
            git config --local user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create tag
        id: create_tag
        run: |
          TAG=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          git tag $TAG
          echo "::set-output name=tag::$TAG"

      - name: Push tag
        if: success()
        run: |
          git push origin ${{ steps.create_tag.outputs.tag }}

      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: 'prod-0'

      - name: Creating Release
        uses: ncipollo/release-action@v1
        with:
          body: |
            Changes in this Release: 
            ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.create_tag.outputs.tag }}
          allowUpdates: true

      - name: Build Android Release
        env:
          APP_BUILD_VERSION: ${{ github.run_number }}
          APP_BINARY_VERSION: ${{ needs.deploy_prod.outputs.latestBinaryVersion }}
        run: |
          expo build:android --release-channel=${{ needs.deploy_prod.outputs.releaseChannel }} > buildLogAndroid.txt
          cat buildLogAndroid.txt

      - name: Parse Asset URL
        id: androidUrl
        run: |
          ASSET_URL=$(cat buildLogAndroid.txt | tail | egrep -o 'https?://expo\.io/artifacts/[^ ]+')
          echo The android url is $ASSET_URL
          echo "::set-output name=assetUrl::$ASSET_URL"

      - name: Download APK Asset
        run: wget -O example-${{ steps.create_tag.outputs.tag }}.apk ${{ steps.androidUrl.outputs.assetUrl }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./example-${{ steps.create_tag.outputs.tag }}.apk
          asset_name: example-${{ steps.create_tag.outputs.tag }}.apk
          tag: ${{ steps.create_tag.outputs.tag }}
